import { VideoDetails, VideoType } from "./video";

export const fakeVideoDB: {[k: number]: VideoDetails} = {
  1726: {
    backdropPath: '/cyecB7godJ6kNHGONFjUyVN9OX5.jpg',
    cast: [
      'Robert Downy Jr.',
      'Terrence Howard',
      'Jeff Bridges',
      'Gwyneth Paltrow',
      'Leslie Bibb',
    ],
    creators: [],
    directors: [
      'Jon Favreau'
    ],
    endDate: null,
    genres: [
      'Action',
      'Science Fiction',
      'Adventure',
    ],
    imdbID: 'tt0371746',
    overview: `With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.`,
    posterPath: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
    rating: 7.6,
    releaseDate: "2008-04-30",
    runtime: 126,
    seasons: null,
    serverID: 1726,
    status: 'Released',
    title: 'Iron Man',
    type: VideoType.Movie,
  },
  1724: {
    backdropPath: '/jPu8yiadqgzwFPGKJmGo637ASVP.jpg',
    cast: [
      'Edward Norton',
      'Liv Tyler',
      'Tim Roth',
      'William Hurt',
      'Tim Blake Nelson',
    ],
    creators: [],
    directors: [
      'Louis Leterrier'
    ],
    endDate: null,
    genres: [
      'Science Fiction',
      'Action',
      'Adventure',
    ],
    imdbID: 'tt0800080',
    overview: `Scientist Bruce Banner scours the planet for an antidote to the unbridled force of rage within him: the Hulk. But when the military masterminds who dream of exploiting his powers force him back to civilization, he finds himself coming face to face with a new, deadly foe.`,
    posterPath: '/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg',
    rating: 6.2,
    releaseDate: '2008-06-12',
    runtime: 114,
    seasons: null,
    serverID: 1724,
    status: 'Released',
    title: 'The Incredible Hulk',
    type: VideoType.Movie,
  },
  10138: {
    backdropPath: '/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg',
    cast: [
      'Robert Downy Jr.',
      'Gwyneth Paltrow',
      'Don Cheadle',
      'Scarlett Johansson',
      'Sam Rockwell',
    ],
    creators: [],
    directors: [
      'Jon Favreau',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Action',
      'Science Fiction',
    ],
    imdbID: 'tt1228705',
    overview: `With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.`,
    posterPath: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
    rating: 6.8,
    releaseDate: '2010-04-28',
    runtime: 124,
    seasons: null,
    serverID: 10138,
    status: 'Released',
    title: 'Iron Man 2',
    type: VideoType.Movie,
  },
  10195: {
    backdropPath: '/1wOu8rdvPxU1ObHi20VcRhfNpbo.jpg',
    cast: [
      'Chris Hemsworth',
      'Natalie Portman',
      'Tom Hiddleston',
      'Anthony Hopkins',
      'Stellan Skarsgård',
    ],
    creators: [],
    directors: [
      'Kenneth Branagh',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Fantasy',
      'Action',
    ],
    imdbID: 'tt0800369',
    overview: `Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.`,
    posterPath: '/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
    rating: 6.8,
    releaseDate: '2011-04-21',
    runtime: 115,
    seasons: null,
    serverID: 10195,
    status: 'Released',
    title: 'Thor',
    type: VideoType.Movie,
  },
  1771: {
    backdropPath: '/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg',
    cast: [
      'Chris Evans',
      'Tommy Lee Jones',
      'Hugo Weaving',
      'Hayley Atwell',
      'Sebastian Stan',
    ],
    creators: [],
    directors: [
      'Joe Johnston',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt0458339',
    overview: `During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.`,
    posterPath: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
    rating: 7.0,
    releaseDate: '2011-07-22',
    runtime: 124,
    seasons: null,
    serverID: 1771,
    status: 'Released',
    title: 'Captain America: The First Avenger',
    type: VideoType.Movie,
  },
  24428: {
    backdropPath: '/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg',
    cast: [
      'Robert Downey Jr.',
      'Chris Evans',
      'Mark Ruffalo',
      'Chris Hemsworth',
      'Scarlett Johansson',
    ],
    creators: [],
    directors: [
      'Joss Whedon',
    ],
    endDate: null,
    genres: [
      'Science Fiction',
      'Action',
      'Adventure',
    ],
    imdbID: 'tt0848228',
    overview: `When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!`,
    posterPath: '/tYqp6vEOo8YlVWrYQvt9nyOhsA2.jpg',
    rating: 7.7,
    releaseDate: '2012-04-25',
    runtime: 143,
    seasons: null,
    serverID: 24428,
    status: 'Released',
    title: 'The Avengers',
    type: VideoType.Movie,
  },
  68721: {
    backdropPath: '/tKa1gmGKAUVYnflYcadipeL3d9h.jpg',
    cast: [
      'Robert Downey Jr.',
      'Gwyneth Paltrow',
      'Don Cheadle',
      'Guy Pearce',
      'Rebecca Hall',
    ],
    creators: [],
    directors: [
      'Shane Black',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt1300854',
    overview: `When Tony Stark's world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.`,
    posterPath: '/qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg',
    rating: 7.7,
    releaseDate: '2013-04-18',
    runtime: 130,
    seasons: null,
    serverID: 68721,
    status: 'Released',
    title: 'Iron Man 3',
    type: VideoType.Movie,
  },
  76338: {
    backdropPath: '/4zTsF0RtO0av3YX1NaKDqGKPxYF.jpg',
    cast: [
      'Chris Hemsworth',
      'Natalie Portman',
      'Tom Hiddleston',
      'Anthony Hopkins',
      'Christopher Eccleston',
    ],
    creators: [],
    directors: [
      'Alan Taylor',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    imdbID: 'tt1981115',
    overview: `Thor fights to restore order across the cosmos… but an ancient race led by the vengeful Malekith returns to plunge the universe back into darkness. Faced with an enemy that even Odin and Asgard cannot withstand, Thor must embark on his most perilous and personal journey yet, one that will reunite him with Jane Foster and force him to sacrifice everything to save us all.`,
    posterPath: '/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg',
    rating: 6.6,
    releaseDate: '2013-10-30',
    runtime: 112,
    seasons: null,
    serverID: 76338,
    status: 'Released',
    title: 'Thor: The Dark World',
    type: VideoType.Movie,
  },
  100402: {
    backdropPath: '/yHB0eNR8rvCpn0VdghEwBsXAC0N.jpg',
    cast: [
      'Chris Evans',
      'Scarlett Johansson',
      'Sebastian Stan',
      'Anthony Mackie',
      'Cobie Smulders',
    ],
    creators: [],
    directors: [
      'Anthony Russo',
      'Joe Russo',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt1843866',
    overview: `After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.`,
    posterPath: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    rating: 7.7,
    releaseDate: '2014-03-20',
    runtime: 136,
    seasons: null,
    serverID: 100402,
    status: 'Released',
    title: 'Captain America: The Winter Soldier',
    type: VideoType.Movie,
  },
  118340: {
    backdropPath: '/2UFxrUHVuSK3Tth7DvQQlF4mGTd.jpg',
    cast: [
      'Chris Pratt',
      'Zoe Saldaña',
      'Dave Bautista',
      'Vin Diesel',
      'Bradley Cooper',
    ],
    creators: [],
    directors: [
      'James Gunn',
    ],
    endDate: null,
    genres: [
      'Action',
      'Science Fiction',
      'Adventure',
    ],
    imdbID: 'tt2015381',
    overview: `Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.`,
    posterPath: '/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
    rating: 7.9,
    releaseDate: '2014-07-30',
    runtime: 121,
    seasons: null,
    serverID: 118340,
    status: 'Released',
    title: 'Guardians of the Galaxy',
    type: VideoType.Movie,
  },
  99861: {
    backdropPath: '/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg',
    cast: [
      'Robert Downey Jr.',
      'Chris Hemsworth',
      'Mark Ruffalo',
      'Chris Evans',
      'Scarlett Johansson',
    ],
    creators: [],
    directors: [
      'Joss Whedon',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt2395427',
    overview: `When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.`,
    posterPath: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
    rating: 7.3,
    releaseDate: '2015-04-22',
    runtime: 141,
    seasons: null,
    serverID: 99861,
    status: 'Released',
    title: 'Avengers: Age of Ultron',
    type: VideoType.Movie,
  },
  102899: {
    backdropPath: '/a7sAqMKv5tkAdMzFfIhPqIBmQ9g.jpg',
    cast: [
      'Paul Rudd',
      'Michael Douglas',
      'Evangeline Lilly',
      'Bobby Cannavale',
      'Corey Stoll',
    ],
    creators: [],
    directors: [
      'Peyton Reed',
    ],
    endDate: null,
    genres: [
      'Science Fiction',
      'Action',
      'Adventure',
    ],
    imdbID: 'tt0478970',
    overview: `Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.`,
    posterPath: '/4FoaB98wCsfWtLqoeDFvKc5CVqf.jpg',
    rating: 7.1,
    releaseDate: '2015-07-14',
    runtime: 117,
    seasons: null,
    serverID: 102899,
    status: 'Released',
    title: 'Ant-Man',
    type: VideoType.Movie,
  },
  271110: {
    backdropPath: '/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg',
    cast: [
      'Chris Evans',
      'Robert Downey Jr.',
      'Scarlett Johansson',
      'Sebastian Stan',
      'Anthony Mackie',
    ],
    creators: [],
    directors: [
      'Anthony Russo',
      'Joe Russo',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Action',
      'Science Fiction',
    ],
    imdbID: 'tt3498820',
    overview: `Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.`,
    posterPath: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
    rating: 7.4,
    releaseDate: '2016-04-27',
    runtime: 147,
    seasons: null,
    serverID: 271110,
    status: 'Released',
    title: 'Captain America: Civil War',
    type: VideoType.Movie,
  },
  284052: {
    backdropPath: '/qUv51IFUvVRAP2379ThmA3eLJx6.jpg',
    cast: [
      'Benedict Cumberbatch',
      'Chiwetel Ejiofor',
      'Rachel McAdams',
      'Benedict Wong',
      'Mads Mikkelsen',
    ],
    creators: [],
    directors: [
      'Scott Derrickson',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    imdbID: 'tt1211837',
    overview: `After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.`,
    posterPath: '/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg',
    rating: 7.4,
    releaseDate: '2016-10-25',
    runtime: 115,
    seasons: null,
    serverID: 284052,
    status: 'Released',
    title: 'Doctor Strange',
    type: VideoType.Movie,
  },
  283995: {
    backdropPath: '/aJn9XeesqsrSLKcHfHP4u5985hn.jpg',
    cast: [
      'Chris Pratt',
      'Zoe Saldaña',
      'Dave Bautista',
      'Vin Diesel',
      'Bradley Cooper',
    ],
    creators: [],
    directors: [
      'James Gunn',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Action',
      'Science Fiction',
    ],
    imdbID: 'tt3896198',
    overview: `The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.`,
    posterPath: '/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg',
    rating: 7.6,
    releaseDate: '2017-04-19',
    runtime: 137,
    seasons: null,
    serverID: 283995,
    status: 'Released',
    title: 'Guardians of the Galaxy Vol. 2',
    type: VideoType.Movie,
  },
  315635: {
    backdropPath: '/fn4n6uOYcB6Uh89nbNPoU2w80RV.jpg',
    cast: [
      'Tom Holland',
      'Michael Keaton',
      'Robert Downey Jr.',
      'Marisa Tomei',
      'Jon Favreau',
    ],
    creators: [],
    directors: [
      'Jon Watts',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
      'Drama',
    ],
    imdbID: 'tt2250912',
    overview: `Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.`,
    posterPath: '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
    rating: 7.3,
    releaseDate: '2017-07-05',
    runtime: 133,
    seasons: null,
    serverID: 315635,
    status: 'Released',
    title: 'Spider-Man: Homecoming',
    type: VideoType.Movie,
  },
  284053: {
    backdropPath: '/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg',
    cast: [
      'Chris Hemsworth',
      'Tom Hiddleston',
      'Cate Blanchett',
      'Tessa Thompson',
      'Jeff Goldblum',
    ],
    creators: [],
    directors: [
      'Taika Waititi',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
      'Science Fiction',
      'Comedy',
    ],
    imdbID: 'tt3501632',
    overview: `Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.`,
    posterPath: '/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg',
    rating: 7.6,
    releaseDate: '2017-10-24',
    runtime: 131,
    seasons: null,
    serverID: 284053,
    status: 'Released',
    title: 'Thor: Ragnarok',
    type: VideoType.Movie,
  },
  284054: {
    backdropPath: '/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg',
    cast: [
      'Chadwick Boseman',
      'Michael B. Jordan',
      'Lupita Nyong\'o',
      'Danai Gurira',
      'Martin Freeman',
    ],
    creators: [],
    directors: [
      'Ryan Coogler',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt1825683',
    overview: `King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.`,
    posterPath: '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
    rating: 7.4,
    releaseDate: '2018-02-13',
    runtime: 135,
    seasons: null,
    serverID: 284054,
    status: 'Released',
    title: 'Black Panther',
    type: VideoType.Movie,
  },
  299536: {
    backdropPath: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
    cast: [
      'Robert Downey Jr.',
      'Chris Hemsworth',
      'Mark Ruffalo',
      'Chris Evans',
      'Scarlett Johansson',
    ],
    creators: [],
    directors: [
      'Anthony Russo',
      'Joe Russo',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Action',
      'Science Fiction',
    ],
    imdbID: 'tt4154756',
    overview: `As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.`,
    posterPath: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    rating: 8.3,
    releaseDate: '2018-04-25',
    runtime: 149,
    seasons: null,
    serverID: 299536,
    status: 'Released',
    title: 'Avengers: Infinity War',
    type: VideoType.Movie,
  },
  363088: {
    backdropPath: '/iYdgEUE2W2aJkgqfSjf1x3gFfuV.jpg',
    cast: [
      'Paul Rudd',
      'Evangeline Lilly',
      'Michael Peña',
      'Walton Goggins',
      'Bobby Cannavale',
    ],
    creators: [],
    directors: [
      'Peyton Reed',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt5095030',
    overview: `Just when his time under house arrest is about to end, Scott Lang once again puts his freedom at risk to help Hope van Dyne and Dr. Hank Pym dive into the quantum realm and try to accomplish, against time and any chance of success, a very dangerous rescue mission.`,
    posterPath: '/cFQEO687n1K6umXbInzocxcnAQz.jpg',
    rating: 7.0,
    releaseDate: '2018-07-04',
    runtime: 119,
    seasons: null,
    serverID: 363088,
    status: 'Released',
    title: 'Ant-Man and the Wasp',
    type: VideoType.Movie,
  },
  299537: {
    backdropPath: '/iYdgEUE2W2aJkgqfSjf1x3gFfuV.jpg',
    cast: [
      'Brie Larson',
      'Samuel L. Jackson',
      'Ben Mendelsohn',
      'Jude Law',
      'Annette Bening',
    ],
    creators: [],
    directors: [
      'Anna Boden',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt4154664',
    overview: `The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.`,
    posterPath: '/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg',
    rating: 6.9,
    releaseDate: '2019-03-06',
    runtime: 124,
    seasons: null,
    serverID: 299537,
    status: 'Released',
    title: 'Captain Marvel',
    type: VideoType.Movie,
  },
  299534: {
    backdropPath: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    cast: [
      'Robert Downey Jr.',
      'Chris Evans',
      'Mark Ruffalo',
      'Chris Hemsworth',
      'Scarlett Johansson',
    ],
    creators: [],
    directors: [
      'Anthony Russo',
      'Joe Russo',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Science Fiction',
      'Action',
    ],
    imdbID: 'tt4154796',
    overview: `After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.`,
    posterPath: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    rating: 8.3,
    releaseDate: '2019-04-24',
    runtime: 181,
    seasons: null,
    serverID: 299534,
    status: 'Released',
    title: 'Avengers: Endgame',
    type: VideoType.Movie,
  },
  429617: {
    backdropPath: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    cast: [
      'Tom Holland',
      'Samuel L. Jackson',
      'Jake Gyllenhaal',
      'Marisa Tomei',
      'Jo Favreau',
    ],
    creators: [],
    directors: [
      'Jon Watts',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt6320628',
    overview: `Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.`,
    posterPath: '/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg',
    rating: 7.5,
    releaseDate: '2019-06-28',
    runtime: 129,
    seasons: null,
    serverID: 429617,
    status: 'Released',
    title: 'Spider-Man: Far from Home',
    type: VideoType.Movie,
  },
  85271: {
    backdropPath: '/33j33midGw49BBxiqlNZeZ6PZ0O.jpg',
    cast: [
      'Elizabeth Olsen',
      'Paul Bettany',
      'Kathryn Hahn',
      'Teyonah Parris',
      'Randall Park',
    ],
    creators: [
      'Jac Schaeffer',
    ],
    directors: [],
    endDate: '2021-03-05',
    genres: [
      'Sci-Fi & Fantasy',
      'Mystery',
      'Drama',
    ],
    imdbID: 'tt9140560',
    overview: `Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.`,
    posterPath: '/frobUz2X5Pc8OiVZU8Oo5K3NKMM.jpg',
    rating: 8.3,
    releaseDate: '2021-01-15',
    runtime: null,
    seasons: 1,
    serverID: 85271,
    status: 'Ended',
    title: 'WandaVision',
    type: VideoType.TV,
  },
  88396: {
    backdropPath: '/eO8h4fwdjWodPr3awVr5wqMN3Ut.jpg',
    cast: [
      'Anthony Mackie',
      'Sebastian Stan',
      'Wyatt Russell',
      'Erin Kellyman',
      'Daniel Brühl',
    ],
    creators: [
      'Malcolm Spellman',
    ],
    directors: [],
    endDate: '2021-04-23',
    genres: [
      'Action & Adventure',
      'Drama',
    ],
    imdbID: 'tt9208876',
    overview: `Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.`,
    posterPath: '/6kbAMLteGO8yyewYau6bJ683sw7.jpg',
    rating: 7.7,
    releaseDate: '2021-03-19',
    runtime: null,
    seasons: 1,
    serverID: 88396,
    status: 'Ended',
    title: 'The Falcon and the Winter Soldier',
    type: VideoType.TV,
  },
  84958: {
    backdropPath: '/p7PLOCD4bqLV4sJmeLrwvkufHt3.jpg',
    cast: [
      'Tom Hiddleston',
      'Owen Wilson',
      'Sophia Di Martino',
      'Gugu Mbatha-Raw',
      'Jonathan Majors',
    ],
    creators: [
      'Michael Waldron',
    ],
    directors: [],
    endDate: null,
    genres: [
      'Drama',
      'Sci-Fi & Fantasy',
    ],
    imdbID: 'tt9140554',
    overview: `After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.`,
    posterPath: '/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
    rating: 8.2,
    releaseDate: '2021-06-09',
    runtime: null,
    seasons: 1,
    serverID: 84958,
    status: 'Returning Series',
    title: 'Loki',
    type: VideoType.TV,
  },
  497698: {
    backdropPath: '/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg',
    cast: [
      'Scarlett Johansson',
      'Florence Pugh',
      'Rachel Weisz',
      'Ray Winstone',
      'Olga Kurylenko',
    ],
    creators: [],
    directors: [
      'Cate Shortland'
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Sci-Fiction',
    ],
    imdbID: 'tt3480822',
    overview: `Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.`,
    posterPath: '/kwB7d51AIcyzPOBOHLCEZJkmPhQ.jpg',
    rating: 7.4,
    releaseDate: '2021-07-07',
    runtime: 134,
    seasons: null,
    serverID: 497698,
    status: 'Released',
    title: 'Black Widow',
    type: VideoType.Movie,
  },
  91363: {
    backdropPath: '/4N6zEMfZ57zNEQcM8gWeERFupMv.jpg',
    cast: [
      'Jeffrey Wright',
      'Terri Douglas',
      'Matthew Wood',
      'Robin Atkin Downes',
      'Fred Tatasciore',
    ],
    creators: [],
    directors: [],
    endDate: null,
    genres: [
      'Animation',
      'Action & Adventure',
      'Sci-Fi & Fantasy',
    ],
    imdbID: 'tt10168312',
    overview: `Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the Marvel Cinematic Universe and turns it on its head, leading the audience into uncharted territory.`,
    posterPath: '/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg',
    rating: 8.3,
    releaseDate: '2021-08-11',
    runtime: null,
    seasons: 1,
    serverID: 91363,
    status: 'Returning Series',
    title: 'What If...?',
    type: VideoType.TV,
  },
  566525: {
    backdropPath: '/zxWAv1A34kdYslBi4ekMDtgIGUt.jpg',
    cast: [
      'Simu Liu',
      'Tony Leung Chiu-wai',
      'Awkwafina',
      'Zhang Meng\'er',
      'Fala Chen',
    ],
    creators: [],
    directors: [
      'Destin Daniel Cretton'
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    imdbID: 'tt9376612',
    overview: `Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.`,
    posterPath: '/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg',
    rating: 7.6,
    releaseDate: '2021-09-01',
    runtime: 132,
    seasons: null,
    serverID: 566525,
    status: 'Released',
    title: 'Shang-Chi and the Legend of the Ten Rings',
    type: VideoType.Movie,
  },
  524434: {
    backdropPath: '/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg',
    cast: [
      'Gemma Chan',
      'Richard Madden',
      'Angelina Jolie',
      'Kumail Nanjiani',
      'Barry Keoghan',
    ],
    creators: [],
    directors: [
      'Chloé Zhao'
    ],
    endDate: null,
    genres: [
      'Sci-Fi',
      'Action',
      'Adventure',
    ],
    imdbID: 'tt9032400',
    overview: `The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.`,
    posterPath: '/lFByFSLV5WDJEv3KabbdAF959F2.jpg',
    rating: 7.0,
    releaseDate: '2021-11-03',
    runtime: 156,
    seasons: null,
    serverID: 524434,
    status: 'Released',
    title: 'Eternals',
    type: VideoType.Movie,
  },
  88329: {
    backdropPath: '/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg',
    cast: [
      'Jeremy Renner',
      'Hailee Steinfeld',
      'Tony Dalton',
      'Alaqua Cox',
      'Fra Fee',
    ],
    creators: [
      'Jonathan Igla'
    ],
    directors: [],
    endDate: '2021-12-22',
    genres: [
      'Drama',
      'Comedy',
      'Action & Adventure',
    ],
    imdbID: 'tt10160804',
    overview: `Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.`,
    posterPath: '/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg',
    rating: 8.0,
    releaseDate: '2021-11-24',
    runtime: null,
    seasons: 1,
    serverID: 88329,
    status: 'Ended',
    title: 'Hawkeye',
    type: VideoType.TV,
  },
  634649: {
    backdropPath: '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
    cast: [
      'Tom Holland',
      'Zendaya',
      'Benedict Cumberbatch',
      'Jacob Batalon',
      'Jon Favreau',
    ],
    creators: [],
    directors: [
      'Jon Watts'
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Sci-Fi',
    ],
    imdbID: 'tt10872600',
    overview: `Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.`,
    posterPath: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
    rating: 7.0,
    serverID: 634649,
    releaseDate: '2021-12-15',
    runtime: 148,
    seasons: null,
    status: 'Released',
    title: 'Spider-Man: No Way Home',
    type: VideoType.Movie,
  },
  618529: {
    backdropPath: '/iKUwhA4DUxMcNKu5lLSbDFwwilk.jpg',
    cast: [
      'Benedict Cumberbatch',
      'Elizabeth Olsen',
      'Chiwetel Ejiofor',
      'Benedict Wong',
      'Xochitl Gomez',
    ],
    creators: [],
    directors: [
      'Sam Raimi'
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    imdbID: 'tt9419884',
    overview: 'Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.',
    posterPath: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
    rating: 7.363,
    serverID: 618529,
    releaseDate: '2022-05-04',
    runtime: 126,
    seasons: null,
    status: 'Released',
    title: 'Doctor Strange in the Multiverse of Madness',
    type: VideoType.Movie,
  },
  92749: {
    backdropPath: '/iux1vKPT7Vw1AzetZb4Jz6wfYsm.jpg',
    cast: [
      'Oscar Isaac',
      'Ethan Hawke',
      'May Calamawy',
      'Ann Akinjirin',
      'David Ganly',
    ],
    creators: [
      'Jeremy Slater'
    ],
    directors: [],
    endDate: '2022-05-04',
    genres: [
      'Action & Adventure',
      'Sci-Fi & Fantasy',
      'Mystery',
    ],
    imdbID: 'tt10234724',
    overview: `When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.`,
    posterPath: '/vKDUmKO6F9bSKKyHhg7YGbgcEeF.jpg',
    rating: 7.9,
    releaseDate: '2022-03-30',
    runtime: null,
    seasons: 1,
    serverID: 92749,
    status: 'Ended',
    title: 'Moon Knight',
    type: VideoType.TV,
  },
  92782: {
    backdropPath: '/rlCRM7U5g2hcU1O8ylGcqsMYHIP.jpg',
    cast: [
      'Iman Vellani',
      'Matt Lintz',
      'Yasmeen Fletcher',
      'Zenobia Shroff',
      'Mohan Kapur',
    ],
    creators: [
      'Bisha K. Ali'
    ],
    directors: [],
    endDate: '2022-07-13',
    genres: [
      'Sci-Fi & Fantasy',
      'Action & Adventure',
      'Comedy',
    ],
    imdbID: 'tt10857164',
    overview: `A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets superpowers like the heroes she’s always looked up to. Life is easier with superpowers, right?`,
    posterPath: '/ls2Hl8CXmqEHvkDqkN3fRtmDodK.jpg',
    rating: 6.7,
    releaseDate: '2022-06-08',
    runtime: null,
    seasons: 1,
    serverID: 92782,
    status: 'Ended',
    title: 'Ms. Marvel',
    type: VideoType.TV,
  },
  616037: {
    backdropPath: '/jsoz1HlxczSuTx0mDl2h0lxy36l.jpg',
    cast: [
      'Chris Hemsworth',
      'Natalie Portman',
      'Christian Bale',
      'Tessa Thompson',
      'Taika Waititi',
    ],
    creators: [],
    directors: [
      'Taika Waititi'
    ],
    endDate: null,
    genres: [
      'Fantasy',
      'Action',
      'Comedy',
    ],
    imdbID: 'tt10648342',
    overview: `After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.`,
    posterPath: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
    rating: 6.7,
    releaseDate: '2022-07-06',
    runtime: 119,
    seasons: null,
    serverID: 616037,
    status: 'Released',
    title: 'Thor: Love and Thunder',
    type: VideoType.Movie,
  },
  92783: {
    backdropPath: '/9GvhICFMiRQA82vS6ydkXxeEkrd.jpg',
    cast: [
      'Tatiana Maslany',
      'Ginger Gonzaga',
      'Jameela Jamil',
      'Renée Elise Goldsberry',
      'Josh Segarra',
    ],
    creators: [
      'Jessica Gao'
    ],
    directors: [],
    endDate: '2022-10-13',
    genres: [
      'Sci-Fi & Fantasy',
      'Action & Adventure',
      'Comedy',
    ],
    imdbID: 'tt10857160',
    overview: `Jennifer Walters navigates the complicated life of a single, 30-something attorney who also happens to be a green 6-foot-7-inch superpowered hulk.`,
    posterPath: '/hJfI6AGrmr4uSHRccfJuSsapvOb.jpg',
    rating: 6.6,
    releaseDate: '2022-08-18',
    runtime: null,
    seasons: 1,
    serverID: 92783,
    status: 'Ended',
    title: 'She-Hulk: Attorney at Law',
    type: VideoType.TV,
  },
  894205: {
    backdropPath: '/pfAZP7JvTTxqgq7n6A1OYgkAdEW.jpg',
    cast: [
      'Gael García Bernal',
      'Laura Donnelly',
      'Harriet Sansom Harris',
      'Kirk R. Thatcher',
      'Eugenie Bondurant',
    ],
    creators: [],
    directors: [
      'Michael Giacchino'
    ],
    endDate: null,
    genres: [
      'Action',
      'Fantasy',
      'Horror',
    ],
    imdbID: 'tt15318872',
    overview: `On a dark and somber night, a secret cabal of monster hunters emerge from the shadows and gather at the foreboding Bloodstone Temple following the death of their leader. In a strange and macabre memorial to the leader’s life, the attendees are thrust into a mysterious and deadly competition for a powerful relic—a hunt that will ultimately bring them face to face with a dangerous monster.`,
    posterPath: '/jmv7EbqBuEk4V1U7OoSBaxkwawO.jpg',
    rating: 7.1,
    releaseDate: '2022-09-25',
    runtime: 55,
    seasons: null,
    serverID: 894205,
    status: 'Released',
    title: 'Werewolf by Night',
    type: VideoType.Movie,
  },
  505642: {
    backdropPath: '/yYrvN5WFeGYjJnRzhY0QXuo4Isw.jpg',
    cast: [
      'Letitia Wright',
      'Lupita Nyong\'o',
      'Danai Gurira',
      'Winston Duke',
      'Dominique Thorne',
    ],
    creators: [],
    directors: [
      'Ryan Coogler',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt9114286',
    overview: `Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.`,
    posterPath: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    rating: 7.5,
    releaseDate: '2022-11-09',
    runtime: 162,
    seasons: null,
    serverID: 505642,
    status: 'Released',
    title: 'Black Panther: Wakanda Forever',
    type: VideoType.Movie,
  },
  640146: {
    backdropPath: '/8YFL5QQVPy3AgrEQxNYVSgiPEbe.jpg',
    cast: [
      'Paul Rudd',
      'Evangeline Lilly',
      'Jonathan Majors',
      'Michelle Pfeiffer',
      'Michael Douglas',
    ],
    creators: [],
    directors: [
      'Peyton Reed',
    ],
    endDate: null,
    genres: [
      'Adventure',
      'Science Fiction',
      'Comedy',
    ],
    imdbID: 'tt10954600',
    overview: `Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.`,
    posterPath: '/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg',
    rating: null,
    releaseDate: '2023-02-15',
    runtime: 125,
    seasons: null,
    serverID: 640146,
    status: 'Released',
    title: 'Ant-Man and the Wasp: Quantumania',
    type: VideoType.Movie,
  },
  114472: {
    backdropPath: '/tMCM3NFILnmEDRi6zDNdD5TrFLk.jpg',
    cast: [
      'Samuel L. Jackson',
      'Ben Mendelsohn',
      'Kingsley Ben-Adir',
      'Emilia Clarke',
      'Olivia Colman',
    ],
    creators: [
      'Kevin Feige',
      'Brian Michael Bendis',
      'Kyle Bradstreet'
    ],
    directors: [],
    endDate: null,
    genres: [
      'Drama',
      'Sci-Fi & Fantasy',
      'Action & Adventure',
    ],
    imdbID: 'tt13157618',
    overview: `Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.`,
    posterPath: '/ySkya7tPCuT1a4gsewyNzRi9cli.jpg',
    rating: 7.2,
    releaseDate: null,
    runtime: null,
    seasons: 1,
    serverID: 114472,
    status: 'Ended',
    title: 'Secret Invasion',
    type: VideoType.TV,
  },
  447365: {
    backdropPath: '/5YZbUmjbMa3ClvSW1Wj3D6XGolb.jpg',
    cast: [
      'Chris Pratt',
      'Zoe Saldaña',
      'Dave Bautista',
      'Karen Gillan',
      'Pom Klementieff',
      'Vin Diesel',
    ],
    creators: [],
    directors: [
      'James Gunn',
    ],
    endDate: null,
    genres: [
      'Science Fiction',
      'Adventure',
      'Action',
    ],
    imdbID: 'tt6791350',
    overview: `Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.`,
    posterPath: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    rating: 8.0,
    releaseDate: '2023-05-05',
    runtime: 150,
    seasons: null,
    serverID: 447365,
    status: 'Released',
    title: 'Guardians of the Galaxy Vol. 3',
    type: VideoType.Movie,
  },
  122226: {
    backdropPath: '/sWm4ALjmW46c4ipNZmv6rjC2cd8.jpg',
    cast: [
      'Alaqua Cox',
      'Zahn McClarnon',
      'Devery Jacobs',
      'Chaske Spencer',
      'Tantoo Cardinal',
    ],
    creators: [
      'Marion Dayre',
    ],
    directors: [],
    endDate: null,
    genres: [
      'Action & Adventure',
      'Drama',
      'Crime',
    ],
    imdbID: 'tt13966962',
    overview: `After her ruthless behavior in New York City catches up with her in her hometown, Maya Lopez must face her past, reconnect with her Native American roots and embrace the meaning of family and community if she ever hopes to move forward.`,
    posterPath: '/3bv5Dv3YmQfzg5ckQMwzCUQ89hU.jpg',
    rating: null,
    releaseDate: null,
    runtime: null,
    seasons: 1,
    serverID: 122226,
    status: 'In Production',
    title: 'Echo',
    type: VideoType.TV,
  },
  609681: {
    backdropPath: '/3AbHZcRdon7TmpqracuQqgJxOGE.jpg',
    cast: [
      'Brie Larson',
      'Teyonah Parris',
      'Iman Vellani',
      'Lashana Lynch',
      'Samuel L. Jackson',
    ],
    creators: [],
    directors: [
      'Nia DaCosta',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
      'Science Fiction',
    ],
    imdbID: 'tt10676048',
    overview: `Carol Danvers, Monica Rambeau, and Kamala Khan trade places with each other every time they use their powers and must team up to fix their problem.`,
    posterPath: '/iebgAsyL4PCA1kc5yb7Bv0rFp7b.jpg',
    rating: null,
    releaseDate: '2023-07-26',
    runtime: null,
    seasons: null,
    serverID: 609681,
    status: 'Post Production',
    title: 'The Marvels',
    type: VideoType.Movie,
  },
  114471: {
    backdropPath: '/3Wh6RYyoqBHkjugcfVrypjH8qQv.jpg',
    cast: [
      'Dominique Thorne',
      'Anthony Ramos',
      'Lyric Ross',
      'Manny Montana',
      'Harper Anthony',
    ],
    creators: [
      'Chinaka Hodge',
    ],
    directors: [],
    endDate: null,
    genres: [
      'Action & Adventure',
      'Drama',
      'Sci-Fi & Fantasy',
    ],
    imdbID: 'tt13623126',
    overview: `Genius inventor Riri Williams creates the most advanced suit of armor since Iron Man and becomes Ironheart.`,
    posterPath: '/ha1kackPwP1BLtyibzuv5hABiDk.jpg',
    rating: null,
    releaseDate: null,
    runtime: null,
    seasons: 1,
    serverID: 114471,
    status: 'In Production',
    title: 'Ironheart',
    type: VideoType.TV,
  },
  822119: {
    backdropPath: '/qYvpc3qLb0LpGOBS7JOq5RxYt0x.jpg',
    cast: [
      'Anthony Mackie',
      'Tim Blake Nelson',
      'Shira Haas',
      'Danny Ramirez',
      'Carl Lumbly',
    ],
    creators: [],
    directors: [
      'Julius Onah',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
    ],
    imdbID: 'tt14513804',
    overview: `A sequel to Marvel Studios' The Falcon and the Winter Soldier and follows Sam Wilson as the new Captain America.`,
    posterPath: '/3DgdfIoJsGnEvSSvUs5hOAYbZlL.jpg',
    rating: null,
    releaseDate: '2024-05-01',
    runtime: null,
    seasons: null,
    serverID: 822119,
    status: 'Planned',
    title: 'Captain America: New World Order',
    type: VideoType.Movie,
  },
  986056: {
    backdropPath: '/3Wh6RYyoqBHkjugcfVrypjH8qQv.jpg',
    cast: [
      'Florence Pugh',
      'Sebastian Stan',
      'David Harbour',
      'Julia Louis-Dreyfus',
      'Wyatt Russell',
    ],
    creators: [],
    directors: [
      'Jake Schreier',
    ],
    endDate: null,
    genres: [
      'Action',
      'Adventure',
    ],
    imdbID: 'tt20969586',
    overview: `A world without Avengers doesn't mean there's not a group of superheroes. There is a group and they're called the Thunderbolts.`,
    posterPath: '/ha1kackPwP1BLtyibzuv5hABiDk.jpg',
    rating: null,
    releaseDate: '2024-07-24',
    runtime: null,
    seasons: null,
    serverID: 986056,
    status: 'Planned',
    title: 'Thunderbolts',
    type: VideoType.Movie,
  },
  617127: {
    backdropPath: '/hFtJz4TvoiJJcw2ZOMdhK22aU9P.jpg',
    cast: [
      'Mahershala Ali',
      'Delroy Lindo',
      'Aaron Pierre',
    ],
    creators: [],
    directors: [
      'Yann Demange',
    ],
    endDate: null,
    genres: [
      'Action',
      'Fantasy',
    ],
    imdbID: 'tt10671440',
    overview: null,
    posterPath: '/fKqA4rgVJwrM7Gb3tQ9TGHnu8Tr.jpg',
    rating: null,
    releaseDate: '2024-09-04',
    runtime: null,
    seasons: null,
    serverID: 617127,
    status: 'Planned',
    title: 'Blade',
    type: VideoType.Movie,
  },
  138501: {
    backdropPath: '/wPnapuJNdWe27IAE5z2Hieo4Yh.jpg',
    cast: [
      'Kathryn Hahn',
      'Emma Caulfield',
      'Joe Locke',
      'Aubrey Plaza',
      'Ali Ahn',
    ],
    creators: [
      'Jac Schaeffer',
    ],
    directors: [],
    endDate: null,
    genres: [
      'Sci-Fi & Fantasy',
      'Action & Adventure',
      'Comedy',
    ],
    imdbID: 'tt15571732',
    overview: `Follow Agatha Harkness before and after her appearance in WandaVision.`,
    posterPath: '/A4JyrpPCsw57E0JHcZK7TDPVPqP.jpg',
    rating: null,
    releaseDate: null,
    runtime: null,
    seasons: 1,
    serverID: 138501,
    status: 'In Production',
    title: 'Agatha: Coven of Chaos',
    type: VideoType.TV,
  },
  202555: {
    backdropPath: '/5NGuM3zv8KjFg7k0FBZ0UdeLFGv.jpg',
    cast: [
      'Charlie Cox',
      'Vincent D\'Onofrio',
      'Michael Gandolfini',
      'Margarita Levieva',
      'Sandrine Holt',
    ],
    creators: [],
    directors: [],
    endDate: null,
    genres: [],
    imdbID: 'tt20411934',
    overview: `An upcoming Disney+ series featuring Matt Murdock aka Daredevil in the Marvel Cinematic Universe.`,
    posterPath: '/t2MKhbLkSlMduIukClOXFMK9LhP.jpg',
    rating: null,
    releaseDate: null,
    runtime: null,
    seasons: 1,
    serverID: 202555,
    status: 'Panned',
    title: 'Daredevil: Born Again',
    type: VideoType.TV,
  },
}
